/* global console */
// Builds the prototype's public ledger in the F08 contract shape (docs/transparencia/CONTRATO.md):
// envelope {schemaVersion, sequence, previousHash, recordedAt, payload, hash}, hash = SHA-256 of the
// JCS of every envelope field except `hash`. Validates each event against src/lib/ledger/schema.ts
// and writes the downloadable JSON plus ../ledger-data.js (file:// friendly, no fetch).
//   node design/prototipo/ledger/build-ledger.mjs      (Node 24, after npm ci)
// The real seeded ledger and the official verifier come from F08; this only feeds the prototype.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const { ledgerSchema, GENESIS_HASH } = await import('../../../src/lib/ledger/schema.ts');

// JCS (RFC 8785) for the values the contract allows: strings, integers, null, objects.
const canonical = v => Array.isArray(v)
  ? `[${v.map(canonical).join(',')}]`
  : v && typeof v === 'object'
    ? `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`
    : JSON.stringify(v);
const sha256 = text => createHash('sha256').update(text, 'utf8').digest('hex');

function chain(items) {
  let previousHash = GENESIS_HASH;
  const events = items.map(({ recordedAt, payload }, i) => {
    const envelope = { schemaVersion: 1, sequence: String(i + 1), previousHash, recordedAt, payload };
    const hash = sha256(canonical(envelope));
    previousHash = hash;
    return { ...envelope, hash };
  });
  return ledgerSchema.parse(events);
}

const read = name => JSON.parse(readFileSync(join(here, name), 'utf8'));
const real = chain(read('real.source.json'));
const sampleSource = read('sample.source.json');
const sample = chain(sampleSource.events);

writeFileSync(join(here, 'real.json'), JSON.stringify(real, null, 1) + '\n');
writeFileSync(join(here, 'sample.json'), JSON.stringify({ notice: sampleSource.notice, events: sample }, null, 1) + '\n');
writeFileSync(join(here, '..', 'ledger-data.js'),
  '// Generated by ledger/build-ledger.mjs. Do not edit by hand.\n/* global window */\n' +
  `window.VN_LEDGER = ${JSON.stringify({ genesis: GENESIS_HASH, real, sample, sampleIncoming: sampleSource.incoming })};\n`);

console.log(`real: ${real.length} events, head ${real.at(-1).hash.slice(0, 12)}`);
console.log(`sample: ${sample.length} events (+${sampleSource.incoming.length} incoming), head ${sample.at(-1).hash.slice(0, 12)}`);
